# Generated by Django 5.1.4 on 2024-12-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBakar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=100)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PeralatanListrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('daya', models.FloatField()),
                ('waktu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=100)),
                ('total', models.FloatField()),
            ],
        ),
    ]
